CREATE TABLE idempotency_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    method VARCHAR(10) NOT NULL,
    route VARCHAR(255) NOT NULL,
    key VARCHAR(200) NOT NULL,
    request_hash CHAR(64) NOT NULL,
    response_body BYTEA,
    status_code INTEGER NOT NULL DEFAULT 200,
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_idempotency_records_request UNIQUE (actor_user_id, method, route, key)
);

CREATE INDEX idx_idempotency_records_created_at ON idempotency_records (created_at);
