CREATE TABLE mcp_service_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    client_id VARCHAR(191) NOT NULL,
    client_secret_hash VARCHAR(255) NOT NULL,
    previous_client_secret_hash VARCHAR(255),
    previous_secret_expires_at TIMESTAMPTZ,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    disabled_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_mcp_service_accounts_user_id UNIQUE (user_id),
    CONSTRAINT uk_mcp_service_accounts_client_id UNIQUE (client_id)
);

CREATE INDEX idx_mcp_service_accounts_enabled ON mcp_service_accounts (enabled);
