CREATE TABLE tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE tag_translations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tag_id BIGINT NOT NULL REFERENCES tags (id) ON DELETE RESTRICT,
    locale VARCHAR(35) NOT NULL REFERENCES locales (code) ON DELETE RESTRICT,
    name VARCHAR(200) NOT NULL,
    slug VARCHAR(200) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_tag_translations_tag_locale UNIQUE (tag_id, locale),
    CONSTRAINT uk_tag_translations_locale_slug UNIQUE (locale, slug)
);

CREATE TABLE article_tags (
    article_id BIGINT NOT NULL REFERENCES articles (id) ON DELETE CASCADE,
    tag_id BIGINT NOT NULL REFERENCES tags (id) ON DELETE RESTRICT,
    PRIMARY KEY (article_id, tag_id)
);

CREATE INDEX idx_article_tags_tag_article ON article_tags (tag_id, article_id);
