CREATE TABLE articles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    deleted_at TIMESTAMPTZ
);

CREATE INDEX idx_articles_deleted_at ON articles (deleted_at);

CREATE TABLE article_translations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_id BIGINT NOT NULL REFERENCES articles (id) ON DELETE CASCADE,
    locale VARCHAR(35) NOT NULL REFERENCES locales (code) ON DELETE RESTRICT,
    title VARCHAR(300) NOT NULL,
    slug VARCHAR(200) NOT NULL,
    summary TEXT NOT NULL DEFAULT '',
    content TEXT NOT NULL DEFAULT '',
    content_format VARCHAR(32) NOT NULL DEFAULT 'markdown',
    status VARCHAR(32) NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'published', 'archived')),
    published_at TIMESTAMPTZ,
    seo_title VARCHAR(255) NOT NULL DEFAULT '',
    seo_description VARCHAR(500) NOT NULL DEFAULT '',
    canonical_url VARCHAR(1000) NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_article_translations_article_locale UNIQUE (article_id, locale),
    CONSTRAINT uk_article_translations_locale_slug UNIQUE (locale, slug)
);

CREATE INDEX idx_article_translations_public_list ON article_translations (locale, status, published_at DESC);

CREATE TABLE article_categories (
    article_id BIGINT NOT NULL REFERENCES articles (id) ON DELETE CASCADE,
    category_id BIGINT NOT NULL REFERENCES categories (id) ON DELETE RESTRICT,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (article_id, category_id)
);

CREATE UNIQUE INDEX uk_article_categories_primary ON article_categories (article_id) WHERE is_primary;

