@BaseURL= http://localhost:80/api/v1/users
GET {{BaseURL}}


###
POST {{BaseURL}}/register
Content-Type: application/json

{
  "name": "testuser",
  "email": "372525248@qq.com",
  "password": "123456",
  "captcha_id": "yF3Yz4427BObsxcUuVDR",
  "captcha_code": "473501"
}